from datetime import datetime

KAFKA_BROKERS = []
KAFKA_TOPIC = ""
KAFKA_CONSUMER_GROUP_ID = ""


SQL_DATABASE = ""
SQL_HOST = ""
SQL_USER_NAME = ""
SQL_USER_PASSWORD = ""
SQL_TABLE = ""

ELASTIC_HOST = ""
ELASTiC_INDEX = ""